language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
env:
  - REQ_FILE="requirements.txt"
install:
  - pip install -r $REQ_FILE
# command to run tests
script:
  - python mult.py
 
